#!/usr/bin/env python3
"""Add file-derived render metadata without changing curated names or tags."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

from brush_asset_info import inspect_asset


ROOT = Path(__file__).resolve().parents[1]
ASSIGNMENT_RE = re.compile(
    r"\A(?P<banner>(?://[^\n]*\n)*)window\.STOCK_BRUSH_METADATA\s*=\s*"
    r"(?P<payload>\{.*\})\s*;\s*\Z",
    re.DOTALL,
)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", default=str(ROOT / "brush-metadata.js"))
    parser.add_argument("--output", default=str(ROOT / "brush-metadata.js"))
    args = parser.parse_args()

    source_path = Path(args.input)
    match = ASSIGNMENT_RE.match(source_path.read_text())
    if not match:
        raise SystemExit(f"could not parse metadata assignment in {source_path}")

    existing = json.loads(match.group("payload"))
    enriched = {}
    for index, (source, item) in enumerate(existing.items(), 1):
        # Copy these editorial values verbatim. All other values are derived
        # afresh from the source asset so stale build data cannot survive.
        enriched[source] = {
            "name": item["name"],
            "tags": item["tags"],
            **inspect_asset(ROOT / source),
        }
        if index % 250 == 0:
            print(f"inspected {index}/{len(existing)}", flush=True)

    banner = (
        "// Generated by scripts/build_brush_metadata.py. Asset filenames and URLs "
        "remain unchanged.\n"
    )
    body = "window.STOCK_BRUSH_METADATA = " + json.dumps(
        enriched, ensure_ascii=False, separators=(",", ":")
    ) + ";\n"
    Path(args.output).write_text(banner + body)
    print(f"wrote {len(enriched)} enriched metadata entries to {args.output}")


if __name__ == "__main__":
    main()
